name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: /tmp/cache/go
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Install dependencies
        run: go mod tidy

      - name: Build Docker image
        run: |
          docker login ghcr.io -u gucio1200 --password ${{ secrets.GHCR_TOKEN }}
          docker build -t ghcr.io/gucio1200/multus-readiness-controller:${{ github.sha }} .
          docker push ghcr.io/gucio1200/multus-readiness-controller:${{ github.sha }}

