name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1

      - name: Install dependencies
        run: |
          cargo build --release

      - name: Run tests
        run: cargo test --release
